[package]
name = "cli_launcher"
version = "1.0.0"
authors = ["Isak Skoog <skoog.isak@gmail.com>"]
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
walkdir = "2"
freedesktop-desktop-entry = "0.7"
fuzzy-matcher = "0.3"
